# Generated by Django 3.2.7 on 2021-10-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(upload_to='uploads/img'),
        ),
    ]
