# Generated by Django 3.2.7 on 2021-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(default='Không có', max_length=1000),
        ),
    ]
